### ISSUE TITLE
Option to turn context awareness off / hints

### ISSUE THREAD

**Issue by Damianu** [nix-community/nixd#610] opened 2024-10-25 18:40 UTC
**Is your feature request related to a problem? Please describe.**

I am using wrapper function around my modules, for example:

```
{
  dlib,
  ...
}:  dlib.mkModule {

    systemLinux = {
      #Options for linux systems 
    };
    systemDarwin = {
      #Options for darwin systems
    };
    system = {
      #Shared options for darwin/linux
    };
}
```

Which causes autocomplete to not work. (Rightfully so as there is no way for nixd to know that putting code in "system" argument of my function should be treated the same way as putting it in "config" of a module).

**Describe the solution you'd like**

Some way of hinting that argument to function is meant as "config" section of nixos/home-manager module.

Option to simply turn off context awarness would be also acceptable solution for my purposes.

**Describe alternatives you've considered**
I didn't find any way to use autocomplete other than just writing my code in normal module and later copying it over.

I realize my approach to making modules may be a bit unusual and niche, but I think many such unusual setups may benefit from just having context unaware suggestions :)

**Comment by inclyc** [comment] 2024-10-26 00:21
> Some way of hinting that argument to function is meant as "config" section of nixos/home-manager module.

This issue might be addressed in the future through the resolution of https://github.com/nix-community/nixd/issues/482 (i.e. allowing you annotating the attribute with some types, hinting the language server), which is currently in its early stages.

**Comment by inclyc** [comment] 2024-11-15 04:32
Duplicate of https://github.com/nix-community/nixd/issues/486

**Closed by inclyc** 2024-11-15 04:32 UTC
Labels: enhancement
