### ISSUE TITLE
rename function with default parameters not works properly

### ISSUE THREAD

**Issue by luochen1990** [nix-community/nixd#255] opened 2023-09-10 14:52 UTC
Code to reproduce this issue:

```nix
{a ? 1}: {
    x = a;
}
```

Reproduce steps for 1st usage:

1. move cursor on `a` in the 1st line,  and rename it to `b`
2. trigger the *rename* action,  and found the default text is "a ? 1"
3. if you replace "a ? 1" into "b ? 1", then the second line becomes "x = b ? 1;", which is not as expected.
4. if you replace "a ? 1" into "b", then the second line becomes "x = b;", but the first line becomes "{b}: {", which is not as expected.

Reproduce steps for 2nd usage:

1. move cursor on `a` in the 2nd line,  and rename it to `b`
2. trigger the *rename* action,  and found the default text is "a"
3. if you replace "a" into "b", then the second line becomes "x = b;", but the first line becomes "{b}: {", which is not as expected.

Extra Information:

- using VSCode  extension **Nix IDE v0.2.2**
- $ nixd --version
LLVM (http://llvm.org/):
LLVM version 16.0.6
Optimized build.

**Comment by inclyc** [comment] 2023-09-11 02:51
This is a known bug caused by limitations from the official nix parser. It focused on the performance of evaluation, and discarded many information for LSPs. 

The possible solutions are:

1. A new parser that is suitable for LSPs. We have experimental tree-sitter-nix branch, but not merged yet.
2. Just link nil with nixd, we have some private chat on Telegram, discussing about linking the two language server with combined abilities (i.e. static analysis from nil, and evaluation & internal inspect from nixd). But the author of nil does not like this, for some reason.

**Closed** 2024-04-09 16:23 UTC
Labels: bug
