### ISSUE TITLE
VSCode setup doesn't work

### ISSUE THREAD

**Issue by srid** [nix-community/nixd#134] opened 2023-06-15 17:35 UTC
I followed the instructions to the tee: https://github.com/nix-community/nixd/blob/main/docs/editor-setup.md#vscode

The result?

<img width="790" alt="image" src="https://github.com/nix-community/nixd/assets/3998/7a65ed64-2465-4cec-8de1-2c033d7db2e9">

```
[Info  - 1:32:56 PM] Connection to server got closed. Server will restart.
[Error - 1:32:56 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:32:56 PM] Nix client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

Is there anything I can do on my end to get more debug information?

**Comment by srid** [comment] 2023-06-15 17:36
Just realized that nixd segfaults when ran manually:

```
❯ nixd
zsh: segmentation fault  nixd
```

This is on M1 macbook air.

**Comment by srid** [comment] 2023-06-15 17:37
Dup #107

**Comment by inclyc** [comment] 2023-06-15 17:40
Duplicate of #107

**Closed by inclyc** 2023-06-15 17:40 UTC
