### ISSUE TITLE
Suppressing error popups in VSCode / VSCodium.

### ISSUE THREAD

**Issue by mark-c-a** [nix-community/nixd#246] opened 2023-08-15 07:16 UTC
VSCode / VSCodium doesn't have a way (global configuration / extension configuration) to ignore extension errors and therefore it always shows the following error.

![db9b8693e894a22b1ade5452d29f0a948ccb92ec](https://github.com/nix-community/nixd/assets/141345105/e2192105-1693-40da-b099-64dfa27f2b4e)

It happens often - for example when I open a new (unsaved) file and vscode assumes that it’ll have Nix code in it. Or when I modify multiple *nix files by global find / replace.

Could you please add a way to ignore the errors?

Thank you.

**Comment by inclyc** [comment] 2023-08-15 08:35
I guess this issue is caused by this line: https://github.com/nix-community/nixd/blob/d1704af3bc2fffa1cbe70e29d96a1522040aaee5/nixd/lib/Server/Controller.cpp#L785

Currently the draft manager only supports file paths, not URLs. I think it should be fixed by removing this code, and handle URLs properly in for `nixd::DraftStore`.

**Closed** 2023-11-14 12:48 UTC
