### ISSUE TITLE
Non-UTF8 characters appear to break the semantic tokens feature

### ISSUE THREAD

**Issue by pagedMov** [nix-community/nixd#614] opened 2024-11-07 07:12 UTC
**Describe the bug**
Semantic tokens appear to be broken by files that contain non UTF-8 characters.

**Logs (Required)**

Error executing vim.schedule lua callback: ....10.2/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: ....10.2/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:149
: index out of range                                                                                                                                                       
stack traceback:                                                                                                                                                           
        [builtin#36]: at 0x7f16a7547e00                                                                                                                                    
        ....10.2/share/nvim/runtime/lua/vim/lsp/semantic_tokens.lua:304: in function 'handler'                                                                             
        ...wrapped-0.10.2/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''                                                                                    
        vim/_editor.lua: in function <vim/_editor.lua:0>   

**Configuration**

I use nixvim to configure nixd. These are my settings:
```
nixd = {
  enable = true;
  settings = {
    nixd = {
      nixpkgs.expr = "import <nixpkgs> { }";
      formatting.command = "nixfmt";
    };
    options = {
      nixos.expr = "(builtins.getFlake \"github:pagedMov/nixos-config\").nixosConfigurations.xenon.options";
      home.expr = "(builtins.getFlake \"github:pagedMov/nixos-config\").homeConfigurations.xenonHome.options";
    };
  };
};
```

**To Reproduce**
1. Open a file containing non UTF-8 characters ([Here](https://gist.github.com/pagedMov/52da9c798c7a6e853319ca28f1e8be59) is the file I've been using to test fixes/workarounds, it triggers this bug every time)
2. Attempt to do anything that makes calls to the LSP.

**Comment by inclyc** [comment] 2024-11-11 02:58
Duplicate of https://github.com/nix-community/nixd/issues/604.

**Closed by inclyc** 2024-11-11 02:58 UTC
Labels: bug
