### ISSUE TITLE
Crash on NeoVim, code 0, signal 6

### ISSUE THREAD

**Issue by arminveres** [nix-community/nixd#583] opened 2024-08-14 07:47 UTC
**Describe the bug**
When any .nix file is opened the LSP, `nixd` instantly crashes

**Logs (Required)**

https://pastebin.com/QcQKANYP

**Configuration**
```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
local function on_attach(client, bufnr)
    -- enable snipper support
    capabilities.textDocument.completion.completionItem.snippetSupport = true
    -- update default nvim capabilities with those of cmp
    capabilities = require("cmp_nvim_lsp").default_capabilities(capabilities)
    -- Highlight words under current cursor
    require("illuminate").on_attach(client)
end

local lspconfig = require("lspconfig")

lspconfig.nixd.setup({
    on_attach = on_attach,
    capabilities = capabilities,
    -- even with cmd defaulted, the errors still persist.
    cmd = { "nixd", "--inlay-hints", "--semantic-tokens" },
})
```
If you have some custom configuration, please paste it here.

**To Reproduce**
1. Open any nix flake
2. See lsp crashing

**Expected behavior**
LSP not crashing and working

**Additional context**
`nixd` installed through home-manager on NixOS.

**Comment by naufik** [comment] 2024-08-14 09:08
Currently having this issue as well with `nixd` installed from `environment.systemPackages`.

Nixd Version `2.1.2`. Tracking stable on nixpkgs commit `4a92571f9207810b559c9eac203d1f4d79830073`

Seems to crash after the following in the logs:

```sh
<-- reply 1
--> notify progress
<-- textDocument/inlineCompletion(3)
--> notify exit
```

**Comment by inclyc** [comment] 2024-08-14 09:14
Open the same buffer with https://github.com/nix-community/nixd/blob/main/nixd/docs/editors/editors.md#reproducible-editors-environment, is it still crashing?

**Comment by arminveres** [comment] 2024-08-14 11:33
@inclyc No that works fine!

**Comment by inclyc** [comment] 2024-08-14 12:03
> @inclyc No, that works fine! I tried adding it as an overlay, but the result is still the same.

I believe the issue was caused by the editor setup. The client (neovim) is sending some non-UTF-8 encoded data to nixd, which results in a crash. Although this shouldn't cause the language server to crash, it can be worked around by fixing the editor configuration (I'm not sure how, but it's definitely possible since other editors are able to work seamlessly).

I guess it is related to your localization settings.

**Comment by arminveres** [comment] 2024-08-14 12:44
Alright, thanks. Makes sense, although I have no clue where that may come from.

**Comment by inclyc** [comment] 2024-08-17 14:56
Hello @arminveres, I've labeled this issue with *cannot-reproduce*. If you could provide more details about the problem, preferably using the Nix language, it would be greatly helpful. Or alternatively, if there are no further issues to address, we might consider closing this issue?

**Comment by arminveres** [comment] 2024-08-19 20:13
Hi @inclyc, the issue still persists, the only thing I can give, is my [nvim config](https://github.com/arminveres/nvim). If I had time, I had to bisect which plugin could cause this issue, but I cannot for the moment.

**Comment by inclyc** [comment] 2024-08-27 11:46
> EDIT: Seems like the plugin that caused the crash was https://github.com/uga-rosa/ccc.nvim. I guess this can be closed now.

Thanks.

**Closed by inclyc** 2024-08-27 11:46 UTC
Labels: bug, cannot-reproduce
