### ISSUE TITLE
Cannot build on macOS due to failing tests

### ISSUE THREAD

**Issue by starcraft66** [nix-community/nixd#215] opened 2023-07-09 02:58 UTC
I can't build nixd on my macbook pro (apple silicon)

I get the following errors during the test phase:

```
[----------] 6 tests from Expr                                                                                                       
[ RUN      ] Expr.Visitor1                                                                                                           
unknown file: Failure                                                                                                                
C++ exception with description "error: cannot set alternative stack: Operation not permitted" thrown in the test body.               
[  FAILED  ] Expr.Visitor1 (0 ms)                                                                                                    
[ RUN      ] Expr.Visitor2                                                                                                           
unknown file: Failure                                                                                                                
C++ exception with description "error: cannot set alternative stack: Operation not permitted" thrown in the test body.               
[  FAILED  ] Expr.Visitor2 (0 ms)                                                                                                    
[ RUN      ] Expr.CallbackRewrite                                                                                                    
unknown file: Failure                                                                                                                
C++ exception with description "error: cannot set alternative stack: Operation not permitted" thrown in the test body.               
[  FAILED  ] Expr.CallbackRewrite (0 ms)                                                                                             
[ RUN      ] Expr.ParentMapLetSearch                                                                                                 
unknown file: Failure                                                                                                                
C++ exception with description "error: cannot set alternative stack: Operation not permitted" thrown in the test body.               
[  FAILED  ] Expr.ParentMapLetSearch (0 ms)                                                                                          
[ RUN      ] Expr.ParentMapRecSearch
unknown file: Failure
C++ exception with description "error: cannot set alternative stack: Operation not permitted" thrown in the test body.
[  FAILED  ] Expr.ParentMapRecSearch (0 ms)
[ RUN      ] Expr.ParentMapLetNested
unknown file: Failure
C++ exception with description "error: cannot set alternative stack: Operation not permitted" thrown in the test body.
[  FAILED  ] Expr.ParentMapLetNested (0 ms)
[----------] 6 tests from Expr (1 ms total)

[----------] 2 tests from Parser
[ RUN      ] Parser.Basic
unknown file: Failure
C++ exception with description "error: cannot set alternative stack: Operation not permitted" thrown in the test body.
[  FAILED  ] Parser.Basic (0 ms)
[ RUN      ] Parser.parse1
[       OK ] Parser.parse1 (0 ms)
```

**Comment by inclyc** [comment] 2023-07-09 07:34
The ci for darwin builds is passing: https://github.com/nix-community/nixd/actions/runs/5478858846/jobs/9979908723

Can you provide more information (e.g. step-by-step instructions, flake.lock) about how to reproduce this issue?

**Comment by inclyc** [comment] 2023-07-10 03:58
The tests are passing on my machine (apple silicon m1, darwin).

**Comment by kradalby** [comment] 2023-07-10 08:31
Hi, I am also running into this, I've attached my lockfile and the full build/test log.

M2 Air, nothing special I think.

[nixd.log](https://github.com/nix-community/nixd/files/11999519/nixd.log)
[flake.lock.zip](https://github.com/nix-community/nixd/files/11999522/flake.lock.zip)

**Comment by inclyc** [comment] 2023-07-10 08:57
> Hi, I am also running into this, I've attached my lockfile and the full build/test log.
> 
> M2 Air, nothing special I think.
> 
> [nixd.log](https://github.com/nix-community/nixd/files/11999519/nixd.log) [flake.lock.zip](https://github.com/nix-community/nixd/files/11999522/flake.lock.zip)

Is this reproducible on the main branch?

**Comment by kradalby** [comment] 2023-07-10 09:45
I'm still seeing this after changing my input in `flake.nix`:

```
 74 ⋮    │    nixd.url = "github:nix-community/nixd";
    ⋮ 74 │    nixd.url = "github:nix-community/nixd/main";
```

```
❯ darwin-rebuild switch --flake .#kratail
warning: updating lock file '/Users/kradalby/git/dotfiles/flake.lock':
• Updated input 'nixd':
    'github:nix-community/nixd/0d57fd2cded203d6e480e77644ee2faac75a0e80' (2023-07-10)
  → 'github:nix-community/nixd/622b1372c92fdd7e9c620a71ef390be559508374' (2023-07-10)
```

**Comment by inclyc** [comment] 2023-07-10 11:44
I'm using my local machine (Apple MacBook Air M1, 2020) trying to reproduce this issue, OS: Monterey.

With the following command:

```
git clone https://github.com/nix-community/nixd.git
cd nixd
nix build -L .#
```

the git revision is: 622b1372c92fdd7e9c620a71ef390be559508374

And the tests are passing...

It appears that you are using flakes as Nix inputs. However, the package you're referring to is already published in nixpkgs. Have you tried using the package from nixpkgs? Alternatively, you can simply use the commands provided above?

The issue might be caused by some sandboxing tools, is there a reduced minimum flake reproducer?

**Comment by inclyc** [comment] 2023-07-13 10:23
If anyone notices this issue, please help me testing nixd on aarch64-darwin builds!

The instructions:

```
git clone https://github.com/nix-community/nixd.git
cd nixd
nix build -L .#
```

works for me on macOS Monterey. I cannot even reproduce the error commented here.

However, the CI for https://github.com/NixOS/nixpkgs/pull/243122, as well as some comments from other individuals, indicate that there might be an issue encountered in other macOS version or some environment.

**Comment by nifoc** [comment] 2023-07-13 12:58
I am also running into the issue on `Darwin 22.5.0, macOS 13.4.1` (latest Ventura).

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.5.0, macOS 13.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.15.1`
 - channels(daniel): `"darwin"`
 - channels(root): `"nixpkgs-22.05pre340506.5c37ad87222"`
 - nixpkgs: `/nix/store/bs2l3qkcy56kq4vbly3c35k5j45h3pqq-source`
 ```

(I only use flakes, so the `channels(root)` probably doesn't matter)

Not sure what else I can provide, since the test failure is the same (`error: cannot set alternative stack: Operation not permitted`).

**Comment by inclyc** [comment] 2023-07-13 15:53
So this issue is caused by macOS updates?

**Comment by nifoc** [comment] 2023-07-13 22:57
Looks like it I guess. What could cause this? Some new security feature (in the kernel)?

**Comment by evanrichter** [comment] 2023-07-14 02:03
I'm encountering this too, on aarch64-darwin running `macOS 13.4.1 (c)`

oddly, when disabling checks, I get a build error. (with `doCheck = true;` I get failures above during the checkPhase)

overlays:
```nix
    sharedOverlays = [
      utils.overlay
      helix.overlays.default
      nixd.overlays.default
      (final: prev: {
        nixd = prev.nixd.overrideAttrs(f: p: {
          doCheck = false;
        });
      })
    ];
```

<details>
<summary>build log</summary>
<br>

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/rdgkpis9dfavygr355w9zf6l5dnmb7pl-ff5q3zfp0grj2kf4ai95pwq84svm1yx9-source
source root is ff5q3zfp0grj2kf4ai95pwq84svm1yx9-source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
meson flags: --buildtype=release         --libdir=/nix/store/9y09nbcw4cv6817ri1dzdmb11adrf0wp-nixd-nightly/lib --libexecdir=/nix/store/9y09nbcw4cv6817ri1dzdmb11adrf0wp-nixd-nightly/libexec         --bindir=/nix/store/9y09nbcw4cv6817ri1dzdmb11adrf0wp-nixd-nightly/bin --sbindir=/nix/store/9y09nbcw4cv6817ri1dzdmb11adrf0wp-nixd-nightly/sbin         --includedir=/nix/store/9y09nbcw4cv6817ri1dzdmb11adrf0wp-nixd-nightly/include         --mandir=/nix/store/9y09nbcw4cv6817ri1dzdmb11adrf0wp-nixd-nightly/share/man --infodir=/nix/store/9y09nbcw4cv6817ri1dzdmb11adrf0wp-nixd-nightly/share/info         --localedir=/nix/store/9y09nbcw4cv6817ri1dzdmb11adrf0wp-nixd-nightly/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/9y09nbcw4cv6817ri1dzdmb11adrf0wp-nixd-nightly  
The Meson build system
Version: 1.1.0
Source dir: /private/tmp/nix-build-nixd-nightly.drv-0/ff5q3zfp0grj2kf4ai95pwq84svm1yx9-source
Build dir: /private/tmp/nix-build-nixd-nightly.drv-0/ff5q3zfp0grj2kf4ai95pwq84svm1yx9-source/build
Build type: native build
Project name: nixd
Project version: nightly
C compiler for the host machine: clang (clang 11.1.0 "clang version 11.1.0")
C linker for the host machine: clang ld64 609
C++ compiler for the host machine: clang++ (clang 11.1.0 "clang version 11.1.0")
C++ linker for the host machine: clang++ ld64 609
Host machine cpu family: aarch64
Host machine cpu: aarch64
Program git found: NO
Configuring nixd-config.h using configuration
Found pkg-config: /nix/store/anrv5blfnnxnl6na57gmlb49hf7dfnhy-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)
Run-time dependency GTest found: YES 1.12.1
Run-time dependency gtest_main found: YES 1.12.1
Did not find CMake 'cmake'
Found CMake: NO
llvm-config found: YES (/nix/store/wzl545bw8rhh20h1hw8a519j8m2y1bfg-llvm-16.0.1-dev/bin/llvm-config) 16.0.1
Run-time dependency LLVM found: YES 16.0.1
Run-time dependency Boost found: YES 1.82.0 (/nix/store/ilh0vad4bqjcqbvxiif4vdqzsl5s2363-boost-1.82.0-dev)
Library backtrace found: YES
Program lit found: NO

meson.build:38:6: ERROR: Program 'lit' not found or not executable

A full log can be found at /private/tmp/nix-build-nixd-nightly.drv-0/ff5q3zfp0grj2kf4ai95pwq84svm1yx9-source/build/meson-logs/meson-log.txt
```

</details>

**Comment by evanrichter** [comment] 2023-07-14 02:34
update: until #226 is merged, this works to install nixd on aarch64-darwin:

```nix
    # (sharedOverlays is from flake-utils-plus, but just apply these two overlays however you do want to do it)
    sharedOverlays = [
      nixd.overlays.default
      (final: prev: {
        nixd = prev.nixd.overrideAttrs(prevAttrs: {
          doCheck = false;
          # TODO: remove when merged: https://github.com/nix-community/nixd/pull/226
          buildInputs = prevAttrs.buildInputs ++ [ prev.lit ];
        });
      })
    ];
```

**Comment by inclyc** [comment] 2023-07-14 11:39
> @evanrichter wrote:
> update: until #226 is merged, this works to install nixd on aarch64-darwin:
> 
> ```nix
>     # (sharedOverlays is from flake-utils-plus, but just apply these two overlays however you do want to do it)
>     sharedOverlays = [
>       nixd.overlays.default
>       (final: prev: {
>         nixd = prev.nixd.overrideAttrs(prevAttrs: {
>           doCheck = false;
>           # TODO: remove when merged: https://github.com/nix-community/nixd/pull/226
>           buildInputs = prevAttrs.buildInputs ++ [ prev.lit ];
>         });
>       })
>     ];
> ```

Is the compiled binary actually working? (i.e. open some editor and use it as the LSP server)?

**Comment by evanrichter** [comment] 2023-07-14 12:34
@inclyc yes it appears to work fine!

I'm not sure if stack switching (the feature being blocked by the OS for security reasons) is only used by the tests or if it's integral to the operation of nixd. But using nixd in an editor (helix) hasn't crashed yet

**Comment by iFreilicht** [comment] 2023-07-21 14:39
> If anyone notices this issue, please help me testing nixd on aarch64-darwin builds!

I did, and it fails as well. This is the [full build log in a gist](https://gist.github.com/iFreilicht/3767118de68128a59b3468fa9c38f4f0). It seems to contain the exact same `operation not permitted` errors as the original issue.

I also ran `nix-info`:

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.5.0, macOS 13.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs"`
 - channels(feuh): `"stable-22.11-darwin, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 ```

**Comment by inclyc** [comment] 2023-07-23 08:04
I have reproduced this issue after upgrading my Mac to Ventura. I think we may just disable these tests instead of fighting against sandboxes. The compiled binary actually works fine outside of that strange sandbox.

**Closed** 2023-07-31 12:12 UTC
Labels: help wanted

**Comment by iFreilicht** [comment] 2023-07-31 16:06
Can confirm the fix was successful, installation from master now works flawlessly.
