### ISSUE TITLE
can't run example

### ISSUE THREAD

**Issue by zeratax** [nix-community/nixd#271] opened 2023-11-11 03:48 UTC
I used the `nix develop github:nix-community/nixd#nvim` development enviroment and copied the [home-manager example](https://github.com/nix-community/nixd/tree/main/docs/examples/options/home-manager) but i do not get auto completion. well it mainly just seems to use keywords from the buffer to autocomplete, but not home-manager keys.

```console
git clone https://github.com/nix-community/nixd
cd nixd/docs/examples/options/home-manager/
nix develop github:nix-community/nixd#nvim
nvim-lsp  flake.nix
```

![buggy-autocompletion](https://github.com/nix-community/nixd/assets/5024958/616dd0f0-3b76-4248-aa26-1a93b4d9b322)

my `:LspLog` https://gist.github.com/zeratax/84219161eca2ee15cfd6d6ce9d8e2af3

In general I do not understand if a flake is necessary for this to work or if my home-manager config that's yet still missing a flake.nix could also work with autocomplete

**Comment by inclyc** [comment] 2023-11-11 03:57
Are you starting nvim in the directory of `.nixd.json`? 

> In general I do not understand if a flake is necessary for this to work or if my home-manager config that's yet still missing a flake.nix could also work with autocomplete

No, you can also specify normal eval path that contains your hm declarations. e.g.

https://github.com/nix-community/nixd/blob/29904e121cc775e7caaf4fffa6bc7da09376a43b/docs/examples/options/nixos/.nixd.json#L7

**Comment by zeratax** [comment] 2023-11-11 03:58
I updated my issue after you replied, but yes this happens when I do this:

```console
git clone https://github.com/nix-community/nixd
cd nixd/docs/examples/options/home-manager/
nix develop github:nix-community/nixd#nvim
nvim-lsp  flake.nix
```
so with nvim in the same directory as `.nixd.json`

**Comment by inclyc** [comment] 2023-11-11 04:08
This looks like a regression issue introduced in https://github.com/nix-community/nixd/pull/249 .

The latest release version does not contain this PR so I suppose it should work as expected.

 We are developing a new language frontend to address this, but it may require a lot of work to get merged here.

**Comment by zeratax** [comment] 2023-11-11 04:40
ah I see!

> No, you can also specify normal eval path that contains your hm declarations. e.g.
> 
> https://github.com/nix-community/nixd/blob/29904e121cc775e7caaf4fffa6bc7da09376a43b/docs/examples/options/nixos/.nixd.json#L7

adjusted it to
```nix
"(import <home-manager/modules> { configuration = ~/.config/home-manager/home.nix; pkgs = import <nixpkgs> {}; }).options
```
and now it works for me with the latest release! 

(though only if my code is properly indented?)
![not indented](https://github.com/nix-community/nixd/assets/5024958/f8da5ab8-d457-42a2-83a0-44e58417e113)
![indented](https://github.com/nix-community/nixd/assets/5024958/59076bc2-b163-4662-8649-e1b1abd210f5)

**Comment by zeratax** [comment] 2023-11-11 04:50
so testing this some more
`nix develop github:nix-community/nixd#nvim`
works on my home-manager setup but not the example home-manager setup.

my nvim with nixd v1.2.2 works with both.

both of these setups only work though when the line is properly indented.

**Closed** 2024-04-19 12:20 UTC
Labels: bug
